GET http://localhost:5062/inventory
Accept: application/json

###

GET http://localhost:5062/api/inventory
Accept: application/json

###

GET http://localhost:5062/inventory/1

###

GET http://localhost:5062/api/inventory/1
Accept: application/json

###

POST http://localhost:5062/inventory
Content-Type: application/json

{
    "name": "Banana",
    "type": "Fruit",
    "quantity": 30,
    "price": 25.50,
    "expirationDate": "2026-06-10",
    "lastOrdered": "2026-06-01"
}