GET http://localhost:5062/api/inventory
Accept: application/json

###

POST http://localhost:5062/api/auth/signin
Content-Type: application/json

{
    "email": "Tommy@gmail.com",
    "password": "Meat"
}

###

GET http://localhost:5062/api/inventory/1
Accept: application/json

###

POST http://localhost:5062/api/inventory
Content-Type: application/json

{
    "name": "Ribs",
    "type": "Meat",
    "quantity": 5,
    "price": 60,
    "expirationDate": "2026-06-15",
    "lastOrdered": "2026-06-01"
}

###

PUT http://localhost:5062/api/inventory/1
Content-Type: application/json

{
    "id": 1,
    "name": "Pork Cutlet",
    "type": "Meat",
    "quantity": 13,
    "price": 29.75,
    "expirationDate": "2026-06-15",
    "lastOrdered": "2026-06-01"
}

###

DELETE http://localhost:5062/api/inventory/2
Content-Type: application/json

###

GET http://localhost:5062/api/users
Content-Type: application/json

###

POST http://localhost:5062/api/users
Content-Type: application/json

{
    "username": "Tommy",
    "email": "Tommy@gmail.com",
    "password": "Meat",
    "signUpDate": "2026-06-14"
}
